# Generated by Django 5.1.4 on 2025-01-02 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('bike_status', models.CharField(choices=[('available', 'Available for Rent'), ('rented', 'Currently Rented'), ('reserved', 'Reserved'), ('disabled', 'Temporarily Disabled')], default='disabled', max_length=20)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('last_location_update', models.DateTimeField(auto_now=True)),
                ('hardware_status', models.CharField(choices=[('active', 'Active and Ready'), ('inactive', 'Inactive or Unavailable'), ('maintenance', 'Under Maintenance'), ('locked', 'Locked'), ('unlocked', 'Unlocked')], default='inactive', max_length=20)),
                ('last_unlock_time', models.DateTimeField(blank=True, null=True)),
                ('last_lock_time', models.DateTimeField(blank=True, null=True)),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('total_distance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hardware', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bike', to='Bikes.bikehardware')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes_owned', to='Owner.ownerprofile')),
            ],
            options={
                'verbose_name_plural': 'Bikes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hardware_status', 'bike_status'], name='Bikes_bikes_hardwar_0bfee8_idx'), models.Index(fields=['latitude', 'longitude'], name='Bikes_bikes_latitud_78aac4_idx')],
            },
        ),
    ]
