# Generated by Django 5.1.4 on 2025-01-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikehardware',
            name='battery_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='bikehardware',
            name='factory_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bikehardware',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikehardware',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bikehardware',
            name='last_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bikehardware',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bikehardware',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bikehardware',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
