# Generated by Django 5.1.4 on 2025-01-02 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bikes', '0001_initial'),
        ('Owner', '0001_initial'),
        ('Rider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('origin_latitude', models.FloatField(blank=True, null=True)),
                ('origin_longitude', models.FloatField(blank=True, null=True)),
                ('destination_latitude', models.FloatField(blank=True, null=True)),
                ('destination_longitude', models.FloatField(blank=True, null=True)),
                ('origin_map', models.ImageField(blank=True, null=True, upload_to='trip_maps/')),
                ('destination_map', models.ImageField(blank=True, null=True, upload_to='trip_maps/')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(max_length=100)),
                ('trip_canceled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('waiting', 'Waiting'), ('started', 'Started'), ('canceled', 'Canceled'), ('ontrip', 'On Trip'), ('completed', 'Completed')], default='created', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('owner_payout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_processed_at', models.DateTimeField(blank=True, null=True)),
                ('unlock_code', models.CharField(blank=True, max_length=6)),
                ('code_generated_at', models.DateTimeField(null=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bikes.bikes')),
                ('bike_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_given', to='Owner.ownerprofile')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_taken', to='Rider.userprofile')),
            ],
            options={
                'ordering': ['-trip_date'],
            },
        ),
    ]
