# Generated by Django 5.1.4 on 2025-01-02 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Owner', '0001_initial'),
        ('Rider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_latitude', models.FloatField(default=0.0)),
                ('pickup_longitude', models.FloatField(default=0.0)),
                ('destination_latitude', models.FloatField(default=0.0)),
                ('destination_longitude', models.FloatField(default=0.0)),
                ('requested_time', models.DateTimeField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duration', models.DurationField()),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_requests', to='Owner.ownerprofile')),
                ('Rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to='Rider.userprofile')),
            ],
        ),
    ]
